# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a75tfgg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/huyan/Documents/8bitALU_orig01/8bitALU_orig01.cache/wt [current_project]
set_property parent.project_path C:/Users/huyan/Documents/8bitALU_orig01/8bitALU_orig01.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/huyan/Documents/8bitALU_orig01/8bitALU_orig01.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  C:/Users/huyan/Documents/8bitALU_orig01/8bitALU_orig01.srcs/sources_1/new/DMux256bit.v
  C:/Users/huyan/Documents/8bitALU_orig01/8bitALU_orig01.srcs/sources_1/new/RAM.v
  C:/Users/huyan/Documents/8bitALU_orig01/8bitALU_orig01.srcs/sources_1/new/ROM.v
  C:/Users/huyan/Documents/8bitALU_orig01/8bitALU_orig01.srcs/sources_1/new/computer.v
}
read_verilog -library xil_defaultlib {
  C:/Users/huyan/Documents/8bitALU_orig01/8bitALU_orig01.srcs/sources_1/new/ALU.v
  C:/Users/huyan/Documents/8bitALU_orig01/8bitALU_orig01.srcs/sources_1/new/Aregister.v
  C:/Users/huyan/Documents/8bitALU_orig01/8bitALU_orig01.srcs/sources_1/new/Bregister.v
  C:/Users/huyan/Documents/8bitALU_orig01/8bitALU_orig01.srcs/sources_1/new/DMux.v
  C:/Users/huyan/Documents/8bitALU_orig01/8bitALU_orig01.srcs/sources_1/new/DMux16bit.v
  C:/Users/huyan/Documents/8bitALU_orig01/8bitALU_orig01.srcs/sources_1/new/Mux.v
  C:/Users/huyan/Documents/8bitALU_orig01/8bitALU_orig01.srcs/sources_1/new/Mux16bit.v
  C:/Users/huyan/Documents/8bitALU_orig01/8bitALU_orig01.srcs/sources_1/new/Mux256bit.v
  C:/Users/huyan/Documents/8bitALU_orig01/8bitALU_orig01.srcs/sources_1/new/PCcontrol.v
  C:/Users/huyan/Documents/8bitALU_orig01/8bitALU_orig01.srcs/sources_1/new/PCregister.v
  C:/Users/huyan/Documents/8bitALU_orig01/8bitALU_orig01.srcs/sources_1/new/adder.v
  C:/Users/huyan/Documents/8bitALU_orig01/8bitALU_orig01.srcs/sources_1/new/clock_division.v
  C:/Users/huyan/Documents/8bitALU_orig01/8bitALU_orig01.srcs/sources_1/new/counter.v
  C:/Users/huyan/Documents/8bitALU_orig01/8bitALU_orig01.srcs/sources_1/new/instruction_decode.v
  C:/Users/huyan/Documents/8bitALU_orig01/8bitALU_orig01.srcs/sources_1/new/instruction_execute.v
  C:/Users/huyan/Documents/8bitALU_orig01/8bitALU_orig01.srcs/sources_1/new/instruction_fetch.v
  C:/Users/huyan/Documents/8bitALU_orig01/8bitALU_orig01.srcs/sources_1/new/register.v
  C:/Users/huyan/Documents/8bitALU_orig01/8bitALU_orig01.srcs/sources_1/new/register256.v
  C:/Users/huyan/Documents/8bitALU_orig01/8bitALU_orig01.srcs/sources_1/new/seg_led.v
  C:/Users/huyan/Documents/8bitALU_orig01/8bitALU_orig01.srcs/sources_1/new/seg_led_decoder.v
  C:/Users/huyan/Documents/8bitALU_orig01/8bitALU_orig01.srcs/sources_1/new/seg_sel_decoder.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/huyan/Documents/8bitALU_orig01/8bitALU_orig01.srcs/constrs_1/new/const.xdc
set_property used_in_implementation false [get_files C:/Users/huyan/Documents/8bitALU_orig01/8bitALU_orig01.srcs/constrs_1/new/const.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top computer -part xc7a75tfgg484-2 -fanout_limit 400 -fsm_extraction one_hot -keep_equivalent_registers -resource_sharing off -no_lc -shreg_min_size 5


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef computer.dcp
create_report "synth_2_synth_report_utilization_0" "report_utilization -file computer_utilization_synth.rpt -pb computer_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
