##CLK
set_property PACKAGE_PIN H4 [get_ports CLK100MHz]
set_property IOSTANDARD LVCMOS33 [get_ports CLK100MHz]
set_property PACKAGE_PIN Y18 [get_ports CLK3Hz]
set_property IOSTANDARD LVCMOS33 [get_ports CLK3Hz]

#BUTTONS
set_property PACKAGE_PIN F4 [get_ports PROGRAM1]
set_property IOSTANDARD LVCMOS33 [get_ports PROGRAM1]
set_property PACKAGE_PIN C2 [get_ports PROGRAM2]
set_property IOSTANDARD LVCMOS33 [get_ports PROGRAM2] 
set_property PACKAGE_PIN B2 [get_ports MANCLK]
set_property IOSTANDARD LVCMOS33 [get_ports MANCLK] 
##SWITCHES
set_property PACKAGE_PIN AA19 [get_ports ina[0]]
set_property IOSTANDARD LVCMOS33 [get_ports ina[0]]
set_property PACKAGE_PIN V19 [get_ports ina[1]]
set_property IOSTANDARD LVCMOS33 [get_ports ina[1]]
set_property PACKAGE_PIN V18  [get_ports ina[2]]
set_property IOSTANDARD LVCMOS33 [get_ports ina[2]]
set_property PACKAGE_PIN Y19 [get_ports ina[3]]
set_property IOSTANDARD LVCMOS33 [get_ports {ina[3]}]
set_property PACKAGE_PIN V20 [get_ports {inb[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inb[0]}]
set_property PACKAGE_PIN U20 [get_ports {inb[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inb[1]}]
set_property PACKAGE_PIN AB22 [get_ports {inb[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inb[2]}]
set_property PACKAGE_PIN AB21 [get_ports {inb[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inb[3]}]
#set_property PACKAGE_PIN F4 [get_ports {opcode[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {opcode[0]}]
#set_property PACKAGE_PIN C2 [get_ports {opcode[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {opcode[1]}]
#set_property PACKAGE_PIN B2 [get_ports {opcode[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {opcode[2]}]

##LED
set_property PACKAGE_PIN AA21 [get_ports seg[0]]
set_property IOSTANDARD LVCMOS33 [get_ports seg[0]]
set_property PACKAGE_PIN AA20 [get_ports seg[1]]
set_property IOSTANDARD LVCMOS33 [get_ports seg[1]]
set_property PACKAGE_PIN W22 [get_ports seg[2]]
set_property IOSTANDARD LVCMOS33 [get_ports seg[2]]
set_property PACKAGE_PIN W21 [get_ports seg[3]]
set_property IOSTANDARD LVCMOS33 [get_ports seg[3]]
set_property PACKAGE_PIN T20 [get_ports seg[4]]
set_property IOSTANDARD LVCMOS33 [get_ports seg[4]]
set_property PACKAGE_PIN R19 [get_ports seg[5]]
set_property IOSTANDARD LVCMOS33 [get_ports seg[5]]
set_property PACKAGE_PIN P19 [get_ports seg[6]]
set_property IOSTANDARD LVCMOS33 [get_ports seg[6]]
set_property PACKAGE_PIN U21 [get_ports seg[7]]
set_property IOSTANDARD LVCMOS33 [get_ports seg[7]]

##DIGITRON
set_property PACKAGE_PIN N15 [get_ports {Regout[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Regout[0]}]
set_property PACKAGE_PIN R17 [get_ports {Regout[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Regout[1]}]
set_property PACKAGE_PIN P16 [get_ports {Regout[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Regout[2]}]
set_property PACKAGE_PIN N14 [get_ports {Regout[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Regout[3]}]
set_property PACKAGE_PIN N13 [get_ports {Regout[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Regout[4]}]
set_property PACKAGE_PIN R16 [get_ports {Regout[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Regout[5]}]
set_property PACKAGE_PIN P15 [get_ports {Regout[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Regout[6]}]
set_property PACKAGE_PIN P17 [get_ports {Regout[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Regout[7]}]
set_property PACKAGE_PIN R14 [get_ports {Regsel[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Regsel[0]}]
set_property PACKAGE_PIN R18 [get_ports {Regsel[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Regsel[1]}]
set_property PACKAGE_PIN T18 [get_ports {Regsel[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Regsel[2]}]
set_property PACKAGE_PIN N17 [get_ports {Regsel[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Regsel[3]}]

set_property PACKAGE_PIN P14 [get_ports {MRegout[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MRegout[0]}]
set_property PACKAGE_PIN U18 [get_ports {MRegout[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MRegout[1]}]
set_property PACKAGE_PIN U17 [get_ports {MRegout[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MRegout[2]}]
set_property PACKAGE_PIN AB18 [get_ports {MRegout[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MRegout[3]}]
set_property PACKAGE_PIN AA18 [get_ports {MRegout[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MRegout[4]}]
set_property PACKAGE_PIN W17 [get_ports {MRegout[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MRegout[5]}]
set_property PACKAGE_PIN V17 [get_ports {MRegout[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MRegout[6]}]
set_property PACKAGE_PIN AB20 [get_ports {MRegout[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MRegout[7]}]

#IO PIN
#set_property PACKAGE_PIN Y11 [get_ports {instraddr[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {instraddr[0]}]
#set_property PACKAGE_PIN V13 [get_ports {instraddr[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {instraddr[1]}]
#set_property PACKAGE_PIN U15 [get_ports {instraddr[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {instraddr[2]}]
#set_property PACKAGE_PIN W15 [get_ports {instraddr[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {instraddr[3]}]
#set_property PACKAGE_PIN T16 [get_ports {instraddr[4]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {instraddr[4]}]
#set_property PACKAGE_PIN AB12 [get_ports {instraddr[5]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {instraddr[5]}]
#set_property PACKAGE_PIN Y11 [get_ports {instraddr[6]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {instraddr[6]}]